# Generated by Django 3.1.14 on 2023-12-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20231210_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_stock_avaialble',
            new_name='is_stock_avaialable',
        ),
    ]
