# Generated by Django 3.1.14 on 2023-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'PLACED'), ('SHIPPED', 'SHIPPED'), ('OUT_FOR_DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], max_length=100),
        ),
    ]
